package ru.pes.systeminfoclient.view;

import java.awt.event.ActionEvent;
import java.io.IOException;
import java.lang.reflect.InvocationTargetException;
import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;
import org.apache.log4j.Logger;
import ru.pes.systeminfoclient.utils.SystemInformationUtil;

public class MainPanel extends javax.swing.JPanel {

    private final Set<Integer> BUILDS = new HashSet<>(); // корпуса
    private final Set<String> DEPARTMENTS = new HashSet<>(); // кафедры
    private final Map<String, Set<String>> ROOMS = new HashMap<>(); // комнаты
    private static final Logger logger = Logger.getLogger(MainPanel.class);

    public MainPanel() {
        initComponents();
        createBuildsSet();
        createRooms2_19Map();
        setCombBoxBuilds();
        setComboBoxRooms("ТООВПМ");
        cbBuilds.addActionListener((ActionEvent e) -> {
            setComboBoxDeparts(cbBuilds.getSelectedIndex());
        });
        cbDepartments.addActionListener((ActionEvent e) -> {
            if (cbBuilds.getSelectedIndex() == 1) {
                setComboBoxRooms("ТООВПМ19");
            } else {
                if (cbDepartments.getSelectedItem() != null) {
                    setComboBoxRooms(cbDepartments.getSelectedItem().toString());
                }              
            }
        });
    }

    //Список корпусов ИПР
    private void createBuildsSet() {
        BUILDS.add(2);
        BUILDS.add(19);
    }

    //Список комнат
    private void createRooms2_19Map() {
        ROOMS.put("ФАХ", getFAHRooms());
        ROOMS.put("ТООВПМ", getTOOVPM2Rooms());
        ROOMS.put("ТООВПМ19", getTOOVPM19Rooms());
        ROOMS.put("ХТТ", getHTT2Rooms());
    }

    //Список комнат ФАХ, 2 корпус
    private Set<String> getFAHRooms() {
        Set<String> fahRooms = new HashSet<>();
        fahRooms.add("127а");
        fahRooms.add("213а");
        fahRooms.add("213б");
        fahRooms.add("214");
        fahRooms.add("215а");
        fahRooms.add("215б");
        fahRooms.add("216");
        fahRooms.add("217");
        fahRooms.add("218");
        fahRooms.add("219");
        fahRooms.add("220");
        fahRooms.add("221");
        fahRooms.add("222");
        fahRooms.add("223");
        fahRooms.add("225");
        fahRooms.add("226");
        fahRooms.add("227");
        fahRooms.add("228");
        fahRooms.add("229");
        fahRooms.add("231");
        fahRooms.add("234");
        fahRooms.add("235");
        fahRooms.add("236");
        fahRooms.add("237");
        return fahRooms;
    }

    //Список комнат ТООВПМ, 2 корпуса
    private Set<String> getTOOVPM2Rooms() {
        Set<String> toovpm2Rooms = new HashSet<>();
        toovpm2Rooms.add("012");
        toovpm2Rooms.add("101");
        toovpm2Rooms.add("109а");
        toovpm2Rooms.add("110");
        toovpm2Rooms.add("112");
        toovpm2Rooms.add("114");
        toovpm2Rooms.add("116");
        toovpm2Rooms.add("116a");
        toovpm2Rooms.add("137");
        toovpm2Rooms.add("138");
        return toovpm2Rooms;
    }

    //Список комнат ТООВПМ, 19 корпуса
    private Set<String> getTOOVPM19Rooms() {
        Set<String> toovpm19Rooms = new HashSet<>();
        toovpm19Rooms.add("126");
        toovpm19Rooms.add("137");
        return toovpm19Rooms;
    }

    //Список комнат ХТТ, 2 корпуса
    private Set<String> getHTT2Rooms() {
        Set<String> htt2Rooms = new HashSet<>();
        htt2Rooms.add("130");
        htt2Rooms.add("131");
        htt2Rooms.add("132");
        htt2Rooms.add("133");
        htt2Rooms.add("134");
        htt2Rooms.add("135");
        htt2Rooms.add("136");
        return htt2Rooms;
    }

    private void setCombBoxBuilds() {
        createBuildsSet();
        BUILDS.stream().forEach((BUILD) -> {
            cbBuilds.addItem(BUILD);
        });
        setComboBoxDeparts(0);
    }

    private void setComboBoxDeparts(int k) {

        if (k == 0) {
            cbDepartments.removeAllItems();
            cbDepartments.addItem("ТООВПМ");
            cbDepartments.addItem("ФАХ");
            cbDepartments.addItem("ХТТ");
        } else if (k == 1) {
            cbDepartments.removeAllItems();
            cbDepartments.addItem("ТООВПМ");
        }

    }

    private void setComboBoxRooms(String str) {
        cbRooms.removeAllItems();
        ROOMS.get(str).stream().forEach((ROOM) -> {
            cbRooms.addItem(ROOM);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbBuilds = new javax.swing.JComboBox();
        cbRooms = new javax.swing.JComboBox();
        cbDepartments = new javax.swing.JComboBox();
        tfInventoryNumber = new javax.swing.JTextField();
        btnStart = new javax.swing.JButton();
        btnOpen = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 137));

        btnStart.setText("Пуск");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        btnOpen.setText("Открыть");
        btnOpen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cbBuilds, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cbRooms, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(tfInventoryNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnOpen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbBuilds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbRooms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfInventoryNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbDepartments, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(btnOpen)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        try {
            new SysInfoFrame(new SystemInformationUtil(cbBuilds.getSelectedItem() + "-" + cbRooms.getSelectedItem(), cbDepartments.getSelectedItem().toString(), tfInventoryNumber.getText())).setVisible(true);
        } catch (IllegalArgumentException | IllegalAccessException | InvocationTargetException | IOException ex) {
            logger.error("Can't create SystemInformationUtil...", ex);
        }
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenActionPerformed
        try {
            SysInfoFrame sysInfoFrame = new SysInfoFrame(new SystemInformationUtil(SystemInformationUtil.getSystemInformationFromFile()));
            sysInfoFrame.setVisible(true);
        } catch (IOException | ClassNotFoundException ex) {
            logger.error("Can't create SystemInformationUtil...", ex);
        }
    }//GEN-LAST:event_btnOpenActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOpen;
    private javax.swing.JButton btnStart;
    private javax.swing.JComboBox cbBuilds;
    private javax.swing.JComboBox cbDepartments;
    private javax.swing.JComboBox cbRooms;
    private javax.swing.JTextField tfInventoryNumber;
    // End of variables declaration//GEN-END:variables
}
